# Generated by Django 3.0.3 on 2020-06-22 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adress mail')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Prenom')),
                ('password1', models.CharField(default='', max_length=255, verbose_name='Password')),
                ('description', models.TextField(default=' ', help_text='faite une description de vous', max_length=400, verbose_name='Bio')),
                ('tel_number', models.CharField(default=' ', help_text='Numero: (224)', max_length=15, verbose_name='Numero Tel')),
                ('avatar', models.ImageField(default='', upload_to='', verbose_name='image')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('promotteur', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='the publish service type', max_length=200)),
                ('categorie', models.CharField(help_text='possible categorie of the publish service', max_length=300)),
                ('titre', models.CharField(help_text='Mettez un titre accrocheur sur votre annonce', max_length=200)),
                ('parcours', models.TextField(help_text='Decrivez votre parcours', max_length=200)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_content', models.TextField(max_length=300)),
                ('isRead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(help_text='type du service ex: informatique', max_length=100, verbose_name='Type du service')),
            ],
        ),
        migrations.CreateModel(
            name='User_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='notif date')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='simple_user',
            field=models.ManyToManyField(through='ss.User_Notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(help_text='Nom de la categorie', max_length=100, verbose_name='Nom de la categorie')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss.Service')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='annonce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ss.Annonce'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
