# Generated by Django 3.0.3 on 2020-06-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0002_auto_20200622_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='service_type',
            new_name='service',
        ),
    ]
