# Generated by Django 3.0.3 on 2020-07-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0003_auto_20200622_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='promotteur',
            new_name='annonceur',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='biographie',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='parcours',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='titre',
        ),
        migrations.AddField(
            model_name='annonce',
            name='description',
            field=models.TextField(default='', help_text='Decrivez votre annonce', max_length=400),
        ),
        migrations.AddField(
            model_name='annonce',
            name='title',
            field=models.CharField(default='', help_text='Donnez un titre a votre annonce', max_length=100, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(help_text='Les categories possible pour ce service', max_length=300, verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='service',
            field=models.CharField(help_text='Le type de servicd', max_length=200, verbose_name='service'),
        ),
    ]
