# Generated by Django 3.0.3 on 2020-07-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0004_auto_20200702_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='annonceur',
        ),
    ]
