# Generated by Django 3.0.3 on 2020-07-12 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0005_remove_user_annonceur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='service',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='simple_user',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss.Service'),
        ),
        migrations.DeleteModel(
            name='User_Notification',
        ),
        migrations.AddField(
            model_name='interet',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss.Annonce'),
        ),
        migrations.AddField(
            model_name='notification',
            name='interet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ss.Interet'),
            preserve_default=False,
        ),
    ]
