# Generated by Django 3.0.3 on 2020-07-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0006_auto_20200712_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(default='', upload_to='users/profileImages', verbose_name='Image du profil'),
        ),
    ]
