# Generated by Django 3.0.3 on 2020-07-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0007_auto_20200716_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profileImages/', verbose_name='Image du profil'),
        ),
    ]
