# Generated by Django 3.0.3 on 2020-07-27 15:20

from django.db import migrations, models
import ss.models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0008_auto_20200722_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='annonce_image',
            field=models.ImageField(default='', upload_to=ss.models.user_directory_path2),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='', upload_to=ss.models.user_directory_path, verbose_name='Image du profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_number',
            field=models.CharField(default='', help_text='Numero: (224)', max_length=15, verbose_name='Numero Tel'),
        ),
    ]
