# Generated by Django 3.0.3 on 2020-07-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0009_auto_20200727_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annonce',
            new_name='AnnonceModel',
        ),
    ]
